'use strict';
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const storage={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
const state=storage.get('materialsWeek6',{forms:{},properties:[],opinion:'',sliders:{renewable:3,impact:3,durable:3,circular:3},evidence:{},completed:[],sketch:''});
const student=storage.get('bioStudentProfile',{name:'',className:'',group:''});
const escapeHTML=v=>String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const save=()=>storage.set('materialsWeek6',state);
const toast=message=>{const el=$('#material-toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2400)};

const menu=$('#main-nav'),toggle=$('.menu-toggle');toggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open))});$$('#main-nav a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));

const properties=['Nhẹ','Cứng','Mềm','Đàn hồi','Xốp','Dai','Thô','Mịn','Chống nước','Cách nhiệt'];
function renderProperties(){$('#property-chips').innerHTML=properties.map(p=>`<button type="button" class="${state.properties.includes(p)?'selected':''}" data-property="${p}">${p}</button>`).join('');$('#property-count').textContent=`Đã chọn ${state.properties.length} / 3 đặc tính`;$$('[data-property]').forEach(b=>b.addEventListener('click',()=>{const p=b.dataset.property;if(state.properties.includes(p))state.properties=state.properties.filter(x=>x!==p);else if(state.properties.length<3)state.properties.push(p);else{toast('Chọn tối đa 3 đặc tính nổi bật.');return}save();renderProperties()}))}renderProperties();

const forms=['material-card','life-cycle-form','translation-canvas','pitch-builder'];
function formData(form){return Object.fromEntries([...new FormData(form).entries()].map(([k,v])=>[k,String(v).trim()]))}
function restoreForms(){forms.forEach(id=>{const form=$(`#${id}`),data=state.forms[id]||{};Object.entries(data).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v});form.addEventListener('input',()=>{state.forms[id]=formData(form);save();if(id==='pitch-builder')renderPitch()})})}restoreForms();

$$('[data-opinion]').forEach(button=>button.addEventListener('click',()=>{state.opinion=button.dataset.opinion;save();$$('[data-opinion]').forEach(b=>b.classList.toggle('selected',b===button));const messages={yes:'Chưa đủ bằng chứng. Nguồn tự nhiên không tự động làm cho toàn bộ vòng đời bền vững.',no:'Có thể đúng trong một số trường hợp, nhưng kết luận vẫn cần dựa vào cách khai thác, sản xuất, sử dụng và xử lý.',depends:'Chính xác. Cần xem nguồn nguyên liệu, quá trình sản xuất, thời gian sử dụng và cuối vòng đời.'};$('#opinion-feedback').textContent=messages[state.opinion]}));if(state.opinion)$(`[data-opinion="${state.opinion}"]`)?.click();

const criteria=[['renewable','RENEWABLE','Khả năng tái tạo'],['impact','LOW IMPACT','Tác động môi trường thấp'],['durable','DURABLE','Độ bền khi sử dụng'],['circular','CIRCULAR','Khả năng quay lại chu trình']];
function renderSliders(){$('#sustainability-sliders').innerHTML=criteria.map(([key,en,vi])=>`<label class="sustainability-row"><span><b>${en}</b><small>${vi}</small></span><input type="range" min="1" max="5" value="${state.sliders[key]}" data-score="${key}"><strong>${state.sliders[key]}</strong><input type="text" value="${escapeHTML(state.evidence[key])}" data-evidence="${key}" placeholder="Bằng chứng..."></label>`).join('');const total=Object.values(state.sliders).reduce((a,b)=>a+Number(b),0);$('#sustainability-total').textContent=`${total} / 20`;$$('[data-score]').forEach(input=>input.addEventListener('input',()=>{state.sliders[input.dataset.score]=Number(input.value);save();renderSliders()}));$$('[data-evidence]').forEach(input=>input.addEventListener('input',()=>{state.evidence[input.dataset.evidence]=input.value.trim();save()}))}renderSliders();

function renderPitch(){const d=state.forms['pitch-builder']||{};const ready=['choice','because','can','sustainable','proposal'].every(k=>d[k]);$('#pitch-preview').textContent=ready?`Chúng em lựa chọn ${d.choice}. Vật liệu này có ${d.because}, vì vậy đặc tính đó có thể ${d.can}. Vật liệu phù hợp hơn về tính bền vững vì ${d.sustainable}. Chúng em đề xuất sử dụng vật liệu cho ${d.proposal}.`:'Hoàn thành các dòng trên để tạo lập luận trình bày.'}renderPitch();

function setupSketch(){const canvas=$('#material-sketch'),ctx=canvas.getContext('2d');ctx.lineWidth=4;ctx.lineCap='round';ctx.strokeStyle='#163a2b';if(state.sketch){const img=new Image();img.onload=()=>ctx.drawImage(img,0,0,canvas.width,canvas.height);img.src=state.sketch}let drawing=false;const point=e=>{const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}};canvas.addEventListener('pointerdown',e=>{drawing=true;canvas.setPointerCapture(e.pointerId);const p=point(e);ctx.beginPath();ctx.moveTo(p.x,p.y)});canvas.addEventListener('pointermove',e=>{if(!drawing)return;const p=point(e);ctx.lineTo(p.x,p.y);ctx.stroke()});const finish=()=>{if(!drawing)return;drawing=false;state.sketch=canvas.toDataURL('image/png');save()};canvas.addEventListener('pointerup',finish);canvas.addEventListener('pointercancel',finish);$('#clear-material-sketch').addEventListener('click',()=>{ctx.clearRect(0,0,canvas.width,canvas.height);state.sketch='';save()})}setupSketch();

function allFilled(form,names){const data=formData(form);return names.every(n=>(data[n]||'').length>=2)}
function validateActivity(n){if(n===1)return state.properties.length===3&&allFilled($('#material-card'),['material','source','structure','property','function','potential']);if(n===2)return Boolean(state.opinion)&&allFilled($('#life-cycle-form'),['raw','production','use','end'])&&criteria.every(([k])=>(state.evidence[k]||'').length>=2);if(n===3)return allFilled($('#translation-canvas'),['material','property','function','need','opportunity','value'])&&Boolean(state.sketch);if(n===4)return allFilled($('#pitch-builder'),['choice','because','can','sustainable','proposal','exit1','exit2','exit3']);return false}
$$('.complete-material-activity').forEach(button=>button.addEventListener('click',()=>{const n=Number(button.dataset.complete);state.forms[forms[n-1]]=formData($(`#${forms[n-1]}`));if(!validateActivity(n)){toast(n===3?'Hoàn thành các ô và thêm Rapid Sketch.':'Hoàn thành nội dung và bằng chứng của hoạt động.');return}if(!state.completed.includes(n))state.completed.push(n);state.completed.sort();save();renderProgress();toast(`Đã hoàn thành hoạt động ${n}.`)}));
function renderProgress(){const count=state.completed.length;$('#material-progress-text').textContent=`${count} / 4 hoạt động`;$('#material-progress-fill').style.width=`${count*25}%`;$$('[data-progress]').forEach((li,i)=>li.classList.toggle('done',state.completed.includes(i+1)));$$('.complete-material-activity').forEach(b=>{const done=state.completed.includes(Number(b.dataset.complete));b.textContent=done?'✓ Đã hoàn thành':`Hoàn thành hoạt động ${b.dataset.complete}`});$('#print-materials').disabled=count<4;$('#print-materials').title=count<4?'Hoàn thành đủ 4 hoạt động để xuất PDF.':'Xuất phiếu học tập tuần 6'}renderProgress();

function sectionRows(data,labels){return labels.map(([k,l])=>`<div class="report-answer"><strong>${l}</strong><p>${escapeHTML(data[k]).replace(/\n/g,'<br>')}</p></div>`).join('')}
function buildReport(){const card=state.forms['material-card']||{},life=state.forms['life-cycle-form']||{},canvas=state.forms['translation-canvas']||{},pitch=state.forms['pitch-builder']||{};const score=Object.values(state.sliders).reduce((a,b)=>a+Number(b),0);$('#materials-report-student').innerHTML=`<span>Họ và tên: ${escapeHTML(student.name)||'________________'}</span><span>Lớp: ${escapeHTML(student.className)||'________'}</span><span>Nhóm: ${escapeHTML(student.group)||'________'}</span>`;$('#materials-report-content').innerHTML=`<section><h2>1. Material Card</h2><p><b>Ba đặc tính quan sát:</b> ${escapeHTML(state.properties.join(', '))}</p>${sectionRows(card,[['material','Vật liệu'],['source','Nguồn gốc'],['structure','Cấu trúc'],['property','Đặc tính'],['function','Chức năng'],['potential','Tiềm năng thiết kế']])}</section><section><h2>2. Material Life Cycle</h2>${sectionRows(life,[['raw','Nguyên liệu'],['production','Sản xuất'],['use','Sử dụng'],['end','Sau sử dụng']])}<h3>Sustainability Score: ${score} / 20</h3>${criteria.map(([k,en,vi])=>`<p><b>${en} ${state.sliders[k]}/5:</b> ${escapeHTML(state.evidence[k])}</p>`).join('')}</section><section><h2>3. Material Translation Canvas</h2>${sectionRows(canvas,[['material','Material'],['property','Property'],['function','Function'],['need','User Need'],['opportunity','Design Opportunity'],['value','Sustainability Value']])}${state.sketch?`<img class="report-sketch" src="${state.sketch}" alt="Rapid Sketch">`:''}</section><section><h2>4. Material Pitch và Exit Ticket</h2>${sectionRows(pitch,[['choice','Chúng em lựa chọn'],['because','Bởi vì vật liệu có'],['can','Đặc tính có thể'],['sustainable','Bền vững vì'],['proposal','Đề xuất ứng dụng'],['exit1','Điều tôi hiểu khác đi'],['exit2','Đặc tính có tiềm năng'],['exit3','Thử nghiệm tiếp theo']])}</section>`}
$('#print-materials').addEventListener('click',()=>{if(state.completed.length<4){toast('Chỉ có thể xuất PDF sau khi hoàn thành đủ 4 hoạt động.');return}buildReport();document.body.classList.add('printing-materials');window.print();setTimeout(()=>document.body.classList.remove('printing-materials'),900)});window.addEventListener('afterprint',()=>document.body.classList.remove('printing-materials'));
$('#reset-materials').addEventListener('click',()=>{if(!confirm('Xóa toàn bộ câu trả lời, điểm và bản vẽ của Tuần 6?'))return;localStorage.removeItem('materialsWeek6');location.reload()});
