const patterns=[
{id:1,slug:'energy',icon:'☀',title:'Chỉ dùng năng lượng cần thiết',short:'Tận dụng nguồn năng lượng sẵn có, tái tạo và tại chỗ.',nature:'Chim condor lượn trên luồng khí nóng để tìm thức ăn với mức tiêu hao năng lượng rất thấp.',design:'Thu hồi nhiệt, chiếu sáng và thông gió tự nhiên; giảm nhu cầu trước khi bổ sung năng lượng.',question:'Giải pháp có thể đạt cùng chức năng với ít năng lượng hơn không?',tags:['năng lượng','hiệu quả']},
{id:2,slug:'recycle',icon:'↻',title:'Luân chuyển mọi vật liệu',short:'Trong tự nhiên, đầu ra của hệ này trở thành đầu vào của hệ khác.',nature:'Gỗ mục được nấm và nhiều sinh vật phân rã thành các cấu phần có thể tái sử dụng trong hệ sinh thái.',design:'Thiết kế dễ tháo rời, phân loại, sửa chữa và đưa vật liệu trở lại chu trình mới.',question:'Cuối vòng đời, từng vật liệu sẽ đi đâu?',tags:['vật liệu','tuần hoàn']},
{id:3,slug:'resilient',icon:'⌁',title:'Có khả năng phục hồi',short:'Duy trì chức năng nhờ đa dạng, dự phòng, phân tán và tự sửa chữa.',nature:'Thông lodgepole có nón chỉ mở sau nhiệt độ cao, giúp rừng tái sinh sau cháy.',design:'Tạo nhiều con đường thực hiện chức năng quan trọng; tránh một điểm hỏng duy nhất.',question:'Nếu một bộ phận hỏng, toàn hệ còn hoạt động không?',tags:['thích nghi','hệ thống']},
{id:4,slug:'optimize',icon:'≈',title:'Tối ưu thay vì tối đa',short:'Cân bằng hiệu quả với chi phí vật liệu, năng lượng và rủi ro.',nature:'Sinh vật không tăng trưởng vô hạn; đầu tư quá mức vào một đặc tính có thể làm giảm khả năng sống sót.',design:'Tối ưu nhiều mục tiêu trong toàn vòng đời thay vì chỉ tối đa tốc độ, sản lượng hay kích thước.',question:'Ta đang tối ưu toàn hệ hay chỉ một chỉ số?',tags:['cân bằng','hệ thống']},
{id:5,slug:'cooperation',icon:'∞',title:'Tạo lợi ích tương hỗ',short:'Mối quan hệ bền vững tạo giá trị cho nhiều thành phần.',nature:'Nấm rễ giúp cây hấp thụ khoáng; cây cung cấp đường tạo ra từ quang hợp cho nấm.',design:'Tìm cách để đầu ra, hạ tầng hoặc dữ liệu của một bên tạo ích lợi cho bên khác.',question:'Ai khác có thể hưởng lợi từ giải pháp này?',tags:['cộng sinh','hệ thống']},
{id:6,slug:'information',icon:'⌁',title:'Vận hành bằng thông tin',short:'Cảm nhận, truyền tín hiệu và phản hồi để điều chỉnh đúng lúc.',nature:'Cây keo phát tín hiệu ethylene khi bị ăn lá; các cây gần đó tăng chất phòng vệ.',design:'Dùng phản hồi vừa đủ, đúng thời điểm; để người dùng và hệ thống thấy hậu quả của hành động.',question:'Hệ thống cần cảm nhận điều gì để tự điều chỉnh?',tags:['thông tin','phản hồi']},
{id:7,slug:'chemistry',icon:'◌',title:'Dùng hóa học an toàn cho sự sống',short:'Tạo vật liệu trong nước, ở điều kiện thường và có thể phân hủy hữu ích.',nature:'Bọt biển Venus tạo khung silica tinh xảo từ nước biển ở nhiệt độ và áp suất môi trường.',design:'Ưu tiên dung môi nước, ít thành phần độc hại và vật liệu tương thích với chu trình sinh học.',question:'Vật liệu và quy trình có an toàn ở mọi giai đoạn không?',tags:['hóa học','vật liệu']},
{id:8,slug:'resources',icon:'▧',title:'Dùng tài nguyên dồi dào',short:'Ưu tiên vật liệu phổ biến tại chỗ; dùng tài nguyên hiếm thật tiết kiệm.',nature:'Ấu trùng caddisfly gom cát, sỏi, vỏ và cành nhỏ quanh mình để làm vỏ bảo vệ.',design:'Khảo sát vật liệu địa phương, phế phẩm và năng lực sẵn có trước khi nhập tài nguyên hiếm.',question:'Tài nguyên dồi dào nhất quanh bài toán là gì?',tags:['địa phương','vật liệu']},
{id:9,slug:'local',icon:'◎',title:'Thích nghi và đáp ứng tại chỗ',short:'Nhận biết điều kiện, chu kỳ và cơ hội của từng bối cảnh.',nature:'Tổ mối điều chỉnh đường hầm theo gió, độ ẩm, O₂ và CO₂ để duy trì cân bằng.',design:'Thiết kế theo khí hậu, văn hóa, người dùng, vật liệu và hạ tầng địa phương.',question:'Điều kiện riêng nào của nơi này phải định hình giải pháp?',tags:['địa phương','thích nghi']},
{id:10,slug:'shape',icon:'◒',title:'Dùng hình dạng để tạo chức năng',short:'Hình học phù hợp có thể thay thế vật liệu và năng lượng bổ sung.',nature:'Các dạng vây đuôi giúp cá ưu tiên tốc độ, lực đẩy hoặc khả năng cơ động.',design:'Tạo chức năng bằng bề mặt, cấu trúc, nếp gấp và hình học trước khi thêm cơ cấu phức tạp.',question:'Hình dạng có thể làm phần việc của vật liệu hoặc máy móc không?',tags:['hình dạng','hiệu quả']}
];
const process=[['01','Xác định thách thức','Viết nhu cầu bằng một động từ chức năng: giữ mát, bám, lọc, vận chuyển…'],['02','Sinh học hóa câu hỏi','Hỏi: Tự nhiên làm thế nào để thực hiện chức năng này trong điều kiện tương tự?'],['03','Khám phá chiến lược','Tìm trên AskNature; ghi lại cơ chế, không chỉ tên hoặc hình dáng sinh vật.'],['04','Khái quát nguyên lý','Tách logic cốt lõi khỏi ví dụ sinh học để có thể chuyển sang bối cảnh mới.'],['05','Mô phỏng & đánh giá','Tạo giải pháp rồi kiểm tra bằng 10 nguyên lý, bối cảnh, giới hạn và đánh đổi.']];

let query='',activeTag='tất cả',openId=1,done=[];
try{done=JSON.parse(localStorage.getItem('biomimicry-progress')||'[]')}catch{done=[]}
const list=document.getElementById('patternList');
const tagBox=document.getElementById('tagFilters');
const search=document.getElementById('searchInput');

function esc(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function updateProgress(){document.getElementById('progressText').textContent=`${done.length}/10 đã học`;document.getElementById('progressBar').style.width=`${done.length*10}%`}
function renderTags(){const tags=['tất cả',...new Set(patterns.flatMap(p=>p.tags))];tagBox.innerHTML=tags.map(t=>`<button type="button" data-tag="${esc(t)}" class="${t===activeTag?'active':''}">${esc(t)}</button>`).join('')}
function renderPatterns(){const filtered=patterns.filter(p=>(activeTag==='tất cả'||p.tags.includes(activeTag))&&`${p.title} ${p.short} ${p.nature} ${p.design}`.toLowerCase().includes(query.toLowerCase()));list.innerHTML=filtered.map(p=>`<article class="pattern ${openId===p.id?'expanded':''}"><button type="button" class="patternSummary" data-open="${p.id}" aria-expanded="${openId===p.id}"><span class="num">${String(p.id).padStart(2,'0')}</span><span class="pIcon">${esc(p.icon)}</span><span class="pTitle"><b>${esc(p.title)}</b><small>${esc(p.short)}</small></span><span class="expand">${openId===p.id?'−':'+'}</span></button>${openId===p.id?`<div class="patternBody"><div><p class="mini">TỰ NHIÊN LÀM GÌ?</p><p>${esc(p.nature)}</p></div><div><p class="mini">CHUYỂN SANG THIẾT KẾ</p><p>${esc(p.design)}</p></div><aside><p class="mini">CÂU HỎI THIẾT KẾ</p><blockquote>${esc(p.question)}</blockquote><div class="row"><a href="https://toolbox.biomimicry.org/core-concepts/natures-unifying-patterns/${p.slug}/" target="_blank" rel="noreferrer">Đọc nguồn ↗</a><button type="button" data-done="${p.id}" class="${done.includes(p.id)?'checked':''}">${done.includes(p.id)?'✓ Đã học':'Đánh dấu đã học'}</button></div></aside></div>`:''}</article>`).join('');updateProgress()}
tagBox.addEventListener('click',e=>{const b=e.target.closest('[data-tag]');if(!b)return;activeTag=b.dataset.tag;renderTags();renderPatterns()});
list.addEventListener('click',e=>{const opener=e.target.closest('[data-open]');if(opener){const id=Number(opener.dataset.open);openId=openId===id?null:id;renderPatterns();return}const marker=e.target.closest('[data-done]');if(marker){const id=Number(marker.dataset.done);done=done.includes(id)?done.filter(x=>x!==id):[...done,id];localStorage.setItem('biomimicry-progress',JSON.stringify(done));renderPatterns()}});
search.addEventListener('input',e=>{query=e.target.value;renderPatterns()});
document.getElementById('steps').innerHTML=process.map(([n,t,d])=>`<div class="step"><span>${n}</span><h3>${esc(t)}</h3><p>${esc(d)}</p></div>`).join('');
document.getElementById('printChallenge').addEventListener('click',()=>window.print());
renderTags();renderPatterns();
