'use strict';
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const storage={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
const app={progress:storage.get('bioLabProgress',{}),canvas:storage.get('bioLabCanvas',{}),profile:storage.get('bioStudentProfile',{name:'',className:'',group:''}),mission:storage.get('bioMission',{active:0,completed:[],answers:{}}),match:{nature:null,design:null,done:new Set()},quiz:{index:0,score:0,locked:false}};
const toast=(message)=>{const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200)};
const shuffle=a=>a.map(v=>[Math.random(),v]).sort((a,b)=>a[0]-b[0]).map(x=>x[1]);

const journey=[['discover','🌱','Discover'],['observe','🔍','Observe'],['patterns','⌬','Patterns'],['ask','🧬','Ask Nature'],['abstract','◇','Abstract'],['discoverCases','◉','Case Lab'],['design','✎','Design'],['evaluate','🌎','Evaluate'],['quiz','✓','Detective']];
const badges=[['observe','Nature Observer'],['ask','Function Thinker'],['patterns','Pattern Explorer'],['discoverCases','AskNature Explorer'],['design','Biomimicry Designer'],['quiz','Nature Mentor']];
function markProgress(key){if(!app.progress[key]){app.progress[key]=true;storage.set('bioLabProgress',app.progress);renderProgress()}}
function renderProgress(){const done=journey.filter(([k])=>app.progress[k]).length,pct=Math.round(done/journey.length*100);$('#header-progress').textContent=`${pct}%`;$('#drawer-progress').style.width=`${pct}%`;$('#journey-list').innerHTML=journey.map(([k,i,t])=>`<li class="${app.progress[k]?'done':''}"><i>${app.progress[k]?'✓':i}</i><span>${t}</span></li>`).join('');$('#badge-list').innerHTML=badges.map(([k,n])=>`<span class="${app.progress[k]?'earned':''}">${n}</span>`).join('')}
function toggleDrawer(open){$('#progress-drawer').classList.toggle('open',open);$('#progress-drawer').setAttribute('aria-hidden',String(!open));$('.drawer-backdrop').hidden=!open}
$$('[data-open-progress]').forEach(b=>b.addEventListener('click',()=>toggleDrawer(true)));$('.close-drawer').addEventListener('click',()=>toggleDrawer(false));$('.drawer-backdrop').addEventListener('click',()=>toggleDrawer(false));renderProgress();

/* Biomimicry Mission — a sequential, printable learning journey */
const missionSteps=[
 {key:'observe',title:'Observe',vi:'Quan sát',week:'Tuần 3',icon:'⌕',hook:'Tạm quên tên gọi. Hãy nhìn hình dạng, cấu trúc và dấu hiệu về cách sự sống vận hành.',visual:'GÂN LÁ → MẠNG PHÂN NHÁNH',fields:[['object','Đối tượng tự nhiên','Bạn đang quan sát gì?','text'],['form','Form – Hình dạng','Mô tả đường nét, bề mặt, cấu trúc lặp…','textarea'],['environment','Context – Môi trường','Điều kiện sống, tác động hoặc giới hạn nào đáng chú ý?','textarea'],['evidence','Bằng chứng quan sát','Chi tiết nào khiến bạn tò mò? Chỉ ghi điều nhìn thấy, chưa giải thích.','textarea']]},
 {key:'function',title:'Function',vi:'Chức năng',week:'Tuần 3',icon:'ƒ',hook:'Đổi từ danh từ sang động từ. Sinh vật không “là” một hình dạng; nó đang làm một việc.',visual:'FORM → FUNCTION',fields:[['verb','Functional Verb – Động từ chức năng','Ví dụ: làm mát, bám, lọc, phân phối…','text'],['need','Nhu cầu sinh học','Chức năng này giúp sinh vật đáp ứng nhu cầu nào?','textarea'],['evidence','Dấu hiệu Function ↔ Form','Cấu trúc nào có thể hỗ trợ chức năng đó?','textarea']]},
 {key:'asknature',title:'AskNature',vi:'Đặt câu hỏi',week:'Tuần 3–4',icon:'?',hook:'Biologize vấn đề: hỏi về chức năng, không tìm tên một con vật “giống sản phẩm”.',visual:'HOW DOES NATURE…?',fields:[['challenge','Human Challenge – Vấn đề','Vấn đề thiết kế của nhóm là gì?','textarea'],['question','Câu hỏi How does nature…?','Ví dụ: How does nature manage heat without electricity?','text'],['keywords','Từ khóa tìm kiếm','2–4 động từ hoặc cụm từ để tìm trên AskNature','text'],['sources','Nguồn đã mở','Dán liên kết AskNature hoặc nguồn khoa học đã xem','text']]},
 {key:'strategy',title:'Biological Strategy',vi:'Chiến lược sinh học',week:'Tuần 3–4',icon:'◎',hook:'Tên sinh vật chưa phải câu trả lời. Hãy tìm Strategy và Mechanism làm cho chức năng xảy ra.',visual:'ORGANISM → STRATEGY → MECHANISM',fields:[['models','Ba biological models','Liệt kê ít nhất 3 sinh vật/hệ sinh thái đã khảo sát.','textarea'],['selected','Mô hình được chọn','Bạn chọn biological model nào?','text'],['strategy','Biological Strategy','Sinh vật thực hiện chức năng bằng chiến lược gì?','textarea'],['mechanism','Mechanism – Cơ chế','Cấu trúc, quá trình hoặc tương tác nào tạo ra kết quả?','textarea'],['why','Vì sao cơ chế hoạt động?','Giải thích quan hệ nguyên nhân → kết quả.','textarea']]},
 {key:'abstract',title:'Abstract',vi:'Trừu tượng hóa',week:'Tuần 4',icon:'◇',hook:'Bỏ tên sinh vật đi, nhưng giữ lại logic vận hành có thể chuyển sang nhiều bối cảnh.',visual:'BIOLOGY − NAME + LOGIC',fields:[['principle','Design Principle – Nguyên lý thiết kế','Viết một chỉ dẫn tổng quát bắt đầu bằng động từ.','textarea'],['logic','Logic cần giữ lại','Mối quan hệ hình dạng / vật liệu / quá trình → chức năng là gì?','textarea'],['boundaries','Điều kiện và giới hạn','Nguyên lý chỉ hoạt động tốt trong điều kiện nào?','textarea']]},
 {key:'design',title:'Design',vi:'Thiết kế',week:'Tuần 5–7',icon:'✎',hook:'Emulate nguyên lý — không sao chép vẻ ngoài. Tạo ý tưởng có thể kiểm tra và cải tiến.',visual:'PRINCIPLE → IDEA → SKETCH',fields:[['idea','Ý tưởng thiết kế','Giải pháp của bạn làm gì và dành cho ai?','textarea'],['translation','Biology → Design translation','Mỗi yếu tố sinh học được chuyển thành đặc điểm thiết kế nào?','textarea'],['materials','Vật liệu & chế tạo','Vật liệu nào phù hợp, sẵn có và an toàn?','textarea'],['patterns','Nature’s Patterns dùng để đánh giá','Chọn ít nhất 2 nguyên lý tự nhiên và giải thích ngắn.','textarea'],['test','Cách thử nghiệm','Bạn sẽ đo điều gì để biết ý tưởng hoạt động?','textarea']]}
];
const escapeHTML=value=>String(value||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function saveMission(){storage.set('bioMission',app.mission)}
function missionDone(index){return app.mission.completed.includes(index)}
function profileReady(){return ['name','className','group'].every(k=>(app.profile[k]||'').trim().length>0)}
function renderStudentProfile(){
 $('#student-name').value=app.profile.name||'';$('#student-class').value=app.profile.className||'';$('#student-group').value=app.profile.group||'';
 $('#profile-status').textContent=profileReady()?`Đã lưu cho ${app.profile.name} · ${app.profile.className} · ${app.profile.group}. Bạn có thể chỉnh sửa bất cứ lúc nào.`:'Vui lòng điền đủ 3 thông tin để mở khóa Mission 01.';
}
$('#student-profile').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;app.profile={name:form.elements.name.value.trim(),className:form.elements.className.value.trim(),group:form.elements.group.value.trim()};if(!profileReady()){toast('Vui lòng điền đủ Họ và tên, Lớp và Nhóm.');return}storage.set('bioStudentProfile',app.profile);renderStudentProfile();renderMission();toast('Đã lưu hồ sơ. Mission 01 được mở khóa.')});
function renderMission(){
 const count=app.mission.completed.length,pct=Math.round(count/missionSteps.length*100);
 $('#mission-percent').textContent=`${pct}%`;
 $('#mission-progress-fill').style.width=`${pct}%`;
 $('#mission-next').textContent=count===missionSteps.length?'Mission hoàn tất — sẵn sàng xuất phiếu học tập.':`Chặng tiếp theo: ${missionSteps[Math.min(count,5)].vi}`;
 $('#print-mission').disabled=count<missionSteps.length;
 $('#print-mission').title=count<missionSteps.length?`Chỉ có thể xuất PDF sau khi hoàn thành đủ 6 Mission (${count}/6).`:'Xuất phiếu học tập hoàn chỉnh';
 const hasProfile=profileReady();
 $('#mission-rail').innerHTML=missionSteps.map((s,i)=>{const locked=!hasProfile||i>count,complete=missionDone(i),active=hasProfile&&i===app.mission.active;return `<button class="mission-tab ${locked?'locked':''} ${complete?'complete':''} ${active?'active':''}" data-mission-index="${i}" ${locked?'aria-disabled="true"':''}><span>${complete?'✓':s.icon}</span><small>${s.week}</small><strong>${i+1}. ${s.title}</strong><em>${s.vi}</em></button>`}).join('');
 $$('.mission-tab').forEach(button=>button.addEventListener('click',()=>{const i=Number(button.dataset.missionIndex);if(!profileReady()){toast('Điền hồ sơ học sinh trước khi bắt đầu Mission.');return}if(i>app.mission.completed.length){toast('Hoàn thành chặng trước để mở khóa.');return}app.mission.active=i;saveMission();renderMission()}));
 if(hasProfile)renderMissionStage();else $('#mission-stage').innerHTML='<div class="mission-locked-message"><div><span>🔒</span><h3>Mission đang khóa</h3><p>Điền Họ và tên, Lớp và Nhóm ở phía trên để bắt đầu.</p></div></div>';
}
function renderMissionStage(){
 const i=Math.min(app.mission.active,missionSteps.length-1),step=missionSteps[i],answers=app.mission.answers[step.key]||{};
 const fields=step.fields.map(([name,label,placeholder,type])=>`<label><span>${label}</span>${type==='textarea'?`<textarea name="${name}" rows="3" placeholder="${placeholder}">${escapeHTML(answers[name])}</textarea>`:`<input name="${name}" value="${escapeHTML(answers[name])}" placeholder="${placeholder}">`}</label>`).join('');
 const sketch=step.key==='design'?`<div class="mission-sketch-wrap"><div><strong>Concept Sketch</strong><small>Vẽ bằng chuột hoặc bút cảm ứng. Bản vẽ được lưu trên thiết bị này.</small></div><canvas id="mission-sketch" width="1000" height="430" aria-label="Vùng vẽ phác thảo ý tưởng"></canvas><button class="text-btn" id="clear-mission-sketch" type="button">Xóa bản vẽ</button></div>`:'';
 $('#mission-stage').innerHTML=`<article class="mission-task"><header><div class="mission-visual" aria-hidden="true"><b>${step.icon}</b><span>${step.visual}</span></div><div><p class="eyebrow">MISSION ${String(i+1).padStart(2,'0')} · ${step.week}</p><h3>${step.title} <span>— ${step.vi}</span></h3><p>${step.hook}</p></div></header><form id="mission-form">${fields}${sketch}<label class="mission-check"><input type="checkbox" name="confirmed" ${answers.confirmed?'checked':''}><span>Tôi đã dùng bằng chứng và có thể giải thích lựa chọn của mình.</span></label><div class="mission-actions"><button class="primary-btn" type="submit">${missionDone(i)?'Lưu cập nhật':'Hoàn thành & mở khóa'}</button><span>Tiến trình tự lưu trong trình duyệt.</span></div></form></article>`;
 const form=$('#mission-form');
 form.addEventListener('input',()=>captureMission(step,form));
 form.addEventListener('submit',event=>{event.preventDefault();captureMission(step,form);const result=validateMission(step,app.mission.answers[step.key]);if(!result.ok){toast(result.message);form.querySelector(`[name="${result.field}"]`)?.focus();return}if(!missionDone(i))app.mission.completed.push(i);app.mission.completed=[...new Set(app.mission.completed)].sort((a,b)=>a-b);app.mission.active=Math.min(i+1,missionSteps.length-1);saveMission();if(app.mission.completed.length===missionSteps.length){markProgress('design');toast('Biomimicry Mission đã hoàn tất!')}else toast(`Đã mở khóa: ${missionSteps[i+1].vi}`);renderMission()});
 if(step.key==='design')setupMissionSketch(answers.sketch);
}
function captureMission(step,form){const data=app.mission.answers[step.key]||{};step.fields.forEach(([name])=>data[name]=form.elements[name].value.trim());data.confirmed=form.elements.confirmed.checked;app.mission.answers[step.key]=data;saveMission()}
function validateMission(step,data={}){for(const [name,label] of step.fields){if((data[name]||'').trim().length<3)return{ok:false,field:name,message:`Hãy hoàn thành: ${label}.`}}if(!data.confirmed)return{ok:false,field:'confirmed',message:'Hãy xác nhận bạn có thể giải thích lựa chọn.'};if(step.key==='asknature'&&!(/how does nature/i.test(data.question)||/thiên nhiên.+(làm|quản lý|giải quyết|thực hiện)/i.test(data.question)))return{ok:false,field:'question',message:'Câu hỏi nên bắt đầu bằng “How does nature…?”'};if(step.key==='abstract'&&data.principle.length<25)return{ok:false,field:'principle',message:'Nguyên lý cần đủ rõ để người khác có thể áp dụng.'};return{ok:true}}
function setupMissionSketch(saved){
 const canvas=$('#mission-sketch'),ctx=canvas.getContext('2d');ctx.lineWidth=4;ctx.lineCap='round';ctx.strokeStyle='#163a2b';
 if(saved){const img=new Image();img.onload=()=>ctx.drawImage(img,0,0,canvas.width,canvas.height);img.src=saved}
 let drawing=false;const point=e=>{const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}};
 canvas.addEventListener('pointerdown',e=>{drawing=true;canvas.setPointerCapture(e.pointerId);const p=point(e);ctx.beginPath();ctx.moveTo(p.x,p.y)});canvas.addEventListener('pointermove',e=>{if(!drawing)return;const p=point(e);ctx.lineTo(p.x,p.y);ctx.stroke()});const finish=()=>{if(!drawing)return;drawing=false;app.mission.answers.design.sketch=canvas.toDataURL('image/png');saveMission()};canvas.addEventListener('pointerup',finish);canvas.addEventListener('pointercancel',finish);
 $('#clear-mission-sketch').addEventListener('click',()=>{ctx.clearRect(0,0,canvas.width,canvas.height);delete app.mission.answers.design.sketch;saveMission()});
}
function buildMissionReport(){
 const sections=missionSteps.map((step,i)=>{const data=app.mission.answers[step.key]||{};const rows=step.fields.map(([name,label])=>`<div class="report-answer"><strong>${escapeHTML(label)}</strong><p>${escapeHTML(data[name]).replace(/\n/g,'<br>')}</p></div>`).join('');const sketch=step.key==='design'&&data.sketch?`<img class="report-sketch" src="${data.sketch}" alt="Concept Sketch của học sinh">`:'';return `<section><h2>${i+1}. ${step.title} — ${step.vi}</h2>${rows}${sketch}</section>`}).join('');
 $('#mission-report-content').innerHTML=sections;
 $('#report-student-name').textContent=`Họ và tên: ${app.profile.name}`;$('#report-student-class').textContent=`Lớp: ${app.profile.className}`;$('#report-student-group').textContent=`Nhóm: ${app.profile.group}`;
}
$('#print-mission').addEventListener('click',()=>{if(app.mission.completed.length<missionSteps.length){toast('Hoàn thành đủ 6 chặng trước khi xuất PDF.');return}buildMissionReport();document.body.classList.add('printing-mission');window.print();setTimeout(()=>document.body.classList.remove('printing-mission'),800)});
window.addEventListener('afterprint',()=>document.body.classList.remove('printing-mission'));
$('#reset-mission').addEventListener('click',()=>{if(!confirm('Xóa toàn bộ câu trả lời và bản vẽ của Biomimicry Mission? Thông tin học sinh vẫn được giữ lại.'))return;app.mission={active:0,completed:[],answers:{}};saveMission();renderMission();toast('Đã đặt lại Mission.')});
renderStudentProfile();renderMission();

const menu=$('#main-nav'),menuToggle=$('.menu-toggle');menuToggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');menuToggle.setAttribute('aria-expanded',String(open))});$$('#main-nav a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');menuToggle.setAttribute('aria-expanded','false')}));
const reveals=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});$$('.reveal').forEach(e=>reveals.observe(e));
const modules=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){markProgress(e.target.dataset.module);$$('#main-nav a').forEach(a=>a.classList.toggle('active',a.hash===`#${e.target.id}`))}}),{threshold:.25});$$('[data-module]').forEach(e=>modules.observe(e));

const scenarios=[
 {title:'Mũi tàu cao tốc Shinkansen',copy:'Hình dạng mỏ chim bói cá gợi ý cách giảm biến đổi áp suất khi tàu đi qua đường hầm.',answer:'biomimicry',feedback:'Đúng. Thiết kế học Function và Strategy của hình dạng, không chỉ mượn vẻ ngoài.',icon:'↝'},
 {title:'Ghế có hình cánh hoa',copy:'Chiếc ghế tạo cảm giác hữu cơ nhờ đường cong giống cánh hoa, nhưng không học cơ chế sinh học.',answer:'biomorphism',feedback:'Đúng. Đây là Biomorphism: mượn ngôn ngữ hình thức tự nhiên.',icon:'✺'},
 {title:'Tường cây sống',copy:'Công trình sử dụng trực tiếp thực vật để tạo bóng mát, hấp thụ nước và cải thiện vi khí hậu.',answer:'bioutilization',feedback:'Đúng. Đây là Bioutilization vì sinh vật được dùng trực tiếp trong giải pháp.',icon:'♧'},
 {title:'Vật liệu dạng tổ ong',copy:'Cấu trúc lặp lục giác truyền cảm hứng cho lõi vật liệu nhẹ và cứng; chưa chắc đã đánh giá theo hệ nguyên lý tự nhiên.',answer:'bio-inspired',feedback:'Hợp lý. Đây là Bio-inspired Design; muốn gọi Biomimicry cần chứng minh rõ cơ chế và sự phù hợp với sự sống.',icon:'⬡'},
 {title:'Bề mặt tự làm sạch',copy:'Vi cấu trúc kị nước của lá sen được trừu tượng hóa thành bề mặt giảm bám dính của chất lỏng.',answer:'biomimicry',feedback:'Đúng. Chuỗi microstructure → giảm tiếp xúc → tự làm sạch được chuyển sang thiết kế.',icon:'◌'}
];let scenarioIndex=0;
function renderScenario() {const s=scenarios[scenarioIndex];$('#scenario-count').textContent=`SPECIMEN 0${scenarioIndex+1} / 0${scenarios.length}`;$('#scenario-title').textContent=s.title;$('#scenario-copy').textContent=s.copy;$('#scenario-visual').innerHTML=`<span aria-hidden="true" style="position:absolute;right:15%;top:12%;font-size:9rem;color:var(--lime);opacity:.6">${s.icon}</span>`;$('#classification-feedback').innerHTML='<span>?</span><p>Phân loại ví dụ này.</p>'}
$$('[data-classify]').forEach(b=>b.addEventListener('click',()=>{const s=scenarios[scenarioIndex],ok=b.dataset.classify===s.answer;$('#classification-feedback').innerHTML=`<span>${ok?'✓':'↺'}</span><p>${ok?s.feedback:'Chưa chính xác. Hãy hỏi: thiết kế dùng sinh vật trực tiếp, mượn hình, hay học mechanism?'}</p>`;if(ok)markProgress('observe')}));$('#next-scenario').addEventListener('click',()=>{scenarioIndex=(scenarioIndex+1)%scenarios.length;renderScenario()});renderScenario();

const modelDetails={model:['NATURE AS MODEL','Chim bói cá không cho ta “hình con chim”. Nó cho ta một chiến lược chuyển tiếp êm giữa hai môi trường.','Quan sát cấu trúc → hiểu cơ chế → trừu tượng hóa → thử trong bối cảnh mới.'],measure:['NATURE AS MEASURE','Một giải pháp không chỉ cần hoạt động. Nó cần phù hợp với điều kiện để sự sống tiếp tục phát triển.','Hỏi: dùng bao nhiêu năng lượng? vật liệu có quay lại chu trình? hệ thống có thích nghi và phục hồi?'],mentor:['NATURE AS MENTOR','Thiên nhiên không phải kho linh kiện. Đó là người thầy với 3,8 tỷ năm nghiên cứu và phát triển.','Chuyển từ tư duy “khai thác” sang quan sát, tôn trọng, học hỏi và cùng phát triển.']};
$$('[data-model]').forEach(b=>b.addEventListener('click',()=>{$$('.model-card').forEach(x=>x.classList.remove('active'));b.classList.add('active');const d=modelDetails[b.dataset.model];$('#model-detail').innerHTML=`<p class="micro">${d[0]}</p><h3>${d[1]}</h3><p>${d[2]}</p>`}));

const patterns=[
 {short:'Needed energy',en:'Nature uses only the energy it needs',vi:'Thiên nhiên chỉ dùng năng lượng cần thiết',explain:'Năng lượng luôn có chi phí. Sự sống ưu tiên nguồn tái tạo, gần và những quá trình năng lượng thấp.',bio:'Kền kền condor lượn trên luồng khí nóng thay vì vỗ cánh liên tục.',design:'Sạc điện thoại từ bánh xe đạp tận dụng chuyển động sẵn có.',think:'Trong trường, năng lượng nào đang bị dùng khi không cần?'},
 {short:'Cycles',en:'Nature recycles all materials',vi:'Thiên nhiên đưa mọi vật liệu trở lại chu trình',explain:'“Chất thải” của loài này trở thành nguồn vật chất và năng lượng cho loài khác.',bio:'Gỗ mục được nấm và vi sinh vật phân rã thành thành phần cho chu trình mới.',design:'Thảm mô-đun có thể tách sợi và lớp đế để tái sử dụng.',think:'Dòng rác nào có thể trở thành đầu vào cho một hoạt động khác?'},
 {short:'Resilience',en:'Nature is resilient to disturbances',vi:'Thiên nhiên có khả năng phục hồi trước nhiễu động',explain:'Đa dạng, dự phòng, phân tán, tự đổi mới và tự sửa chữa giúp hệ thống duy trì chức năng.',bio:'Rừng thông lodgepole có nón mở trong điều kiện thường và nón mở sau cháy.',design:'Hạ tầng phân tán và vật liệu tự sửa chữa giảm nguy cơ hỏng toàn hệ.',think:'Nếu trường mất điện hoặc Internet, chức năng nào vẫn phải tiếp tục?'},
 {short:'Optimize',en:'Nature tends to optimize rather than maximize',vi:'Thiên nhiên tối ưu thay vì tối đa hóa',explain:'Sự sống cân bằng hiệu quả với năng lượng, vật liệu và nhiều ràng buộc cùng lúc.',bio:'Xương đặt vật liệu tại vùng chịu lực và loại bớt nơi không cần.',design:'Cấu trúc nhẹ dùng topology optimization thay vì tăng độ dày toàn bộ.',think:'Sản phẩm của em đang tối đa một chỉ số và gây tác dụng phụ nào?'},
 {short:'Mutual benefits',en:'Nature provides mutual benefits',vi:'Thiên nhiên tạo ra lợi ích tương hỗ',explain:'Nhiều quan hệ bền vững tồn tại vì các bên trao đổi nguồn lực và cùng có lợi.',bio:'Nấm rễ tăng hấp thu khoáng; cây cung cấp đường từ quang hợp.',design:'Chia sẻ hạ tầng, không gian và dòng vật liệu giữa nhiều tổ chức.',think:'Ai khác có thể hưởng lợi từ giải pháp của em?'},
 {short:'Information',en:'Nature runs on information',vi:'Thiên nhiên vận hành bằng thông tin',explain:'Hệ sống gửi, nhận và đáp ứng tín hiệu qua các vòng phản hồi.',bio:'Chim non phát tín hiệu đói; tín hiệu giảm khi đã được ăn.',design:'Cửa sổ tự mở theo nhiệt độ và CO₂, nhưng vẫn cho người dùng điều khiển.',think:'Giải pháp cần cảm nhận điều gì trước khi hành động?'},
 {short:'Safe chemistry',en:'Nature uses life-friendly chemistry',vi:'Thiên nhiên dùng hóa học an toàn cho sự sống',explain:'Vật liệu được tạo trong điều kiện gần môi trường, thực hiện chức năng rồi có thể phân giải thành thành phần hữu ích.',bio:'Vỏ bào ngư hình thành trong nước biển ở nhiệt độ và áp suất thường.',design:'Chất phủ gốc nước, không độc và được thiết kế cho cuối vòng đời.',think:'Vật liệu an toàn khi dùng nhưng sẽ ra sao khi bỏ đi?'},
 {short:'Abundant resources',en:'Nature builds with abundant resources',vi:'Thiên nhiên xây dựng bằng tài nguyên dồi dào',explain:'Sự sống ưu tiên vật liệu phổ biến tại chỗ và dùng tài nguyên hiếm rất tiết kiệm.',bio:'Ấu trùng caddisfly kết vỏ từ những mảnh vật liệu sẵn có quanh nó.',design:'Xây dựng bằng đất, đá và lao động địa phương phù hợp từng vùng.',think:'Thứ gì quanh trường có thể trở thành vật liệu thiết kế?'},
 {short:'Local response',en:'Nature is locally attuned and responsive',vi:'Thiên nhiên thích nghi và đáp ứng địa phương',explain:'Sinh vật đọc điều kiện tại chỗ, khai thác chu kỳ và phản ứng khi môi trường thay đổi.',bio:'Tổ mối dùng gió, độ xốp và đường hầm để điều tiết khí trong bối cảnh nóng.',design:'Sản xuất theo đơn, gần người dùng và phù hợp điều kiện khí hậu địa phương.',think:'Giải pháp sẽ thay đổi thế nào giữa Hà Nội và Đà Nẵng?'},
 {short:'Shape',en:'Nature uses shape to determine functionality',vi:'Thiên nhiên dùng hình dạng để tạo nên chức năng',explain:'Hình học và cấu trúc tạo chức năng mà không cần liên tục thêm vật liệu hoặc năng lượng.',bio:'Lưỡi mèo có gai nhỏ phục vụ ăn và chải lông.',design:'Mũi Shinkansen giảm sóng áp suất và lực cản nhờ hình dạng.',think:'Có thể thay một bộ phận hoặc nguồn năng lượng bằng hình học không?'}
];
function renderPattern(i=0){$$('.pattern-node').forEach((n,j)=>n.classList.toggle('active',i===j));const p=patterns[i];$('#pattern-inspector').innerHTML=`<p class="pattern-number">PATTERN ${String(i+1).padStart(2,'0')}</p><h3>${p.en}</h3><p><strong>${p.vi}</strong></p><p>${p.explain}</p><h4>Biology Example</h4><p>${p.bio}</p><h4>Design Connection</h4><p>${p.design}</p><p class="think-prompt">THINK → ${p.think}</p>`;markProgress('patterns')}
$('#pattern-orbit').innerHTML=patterns.map((p,i)=>`<button class="pattern-node" data-pattern="${i}"><span>${String(i+1).padStart(2,'0')}</span><small>${p.short}</small></button>`).join('');$$('[data-pattern]').forEach(b=>b.addEventListener('click',()=>renderPattern(+b.dataset.pattern)));renderPattern(0);
$$('.healing-step').forEach(b=>b.addEventListener('click',()=>{$$('.healing-step').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#concrete-demo').classList.toggle('healed',+b.dataset.heal>=2)}));

const matches=[['Lotus leaf','Self-cleaning coating','microtexture → low adhesion'],['Gecko foot','Dry adhesive','microscopic hairs → reversible attachment'],['Termite mound','Passive ventilation','porous tunnels → airflow'],['Kingfisher','Shinkansen nose','streamlined shape → low pressure change'],['Shark skin','Riblet surface','aligned denticles → drag/fouling control'],['Burr','Hook-and-loop fastener','tiny hooks → mechanical attachment'],['Whale fin','Efficient blade edge','tubercles → flow control'],['Honeycomb','Lightweight panel','repeating cells → strength with less material']];
function renderMatch(){const done=app.match.done;$('#nature-options').innerHTML=shuffle(matches.map((m,i)=>({i,t:m[0]}))).map(x=>`<button class="match-option ${done.has(x.i)?'matched':''}" data-nature="${x.i}" ${done.has(x.i)?'disabled':''}>${x.t}</button>`).join('');$('#design-options').innerHTML=shuffle(matches.map((m,i)=>({i,t:m[1]}))).map(x=>`<button class="match-option ${done.has(x.i)?'matched':''}" data-design="${x.i}" ${done.has(x.i)?'disabled':''}>${x.t}</button>`).join('');$('#match-score').textContent=done.size;bindMatch()}
function bindMatch(){$$('[data-nature]').forEach(b=>b.addEventListener('click',()=>{app.match.nature=+b.dataset.nature;$$('[data-nature]').forEach(x=>x.classList.toggle('selected',x===b));checkMatch()}));$$('[data-design]').forEach(b=>b.addEventListener('click',()=>{app.match.design=+b.dataset.design;$$('[data-design]').forEach(x=>x.classList.toggle('selected',x===b));checkMatch()}))}
function checkMatch(){if(app.match.nature===null||app.match.design===null)return;if(app.match.nature===app.match.design){const i=app.match.nature;app.match.done.add(i);$('#match-feedback').textContent=`Đúng! ${matches[i][0]} → ${matches[i][2]} → ${matches[i][1]}`;if(app.match.done.size===8){toast('Badge mở khóa: Pattern Explorer');markProgress('patterns')}app.match.nature=app.match.design=null;setTimeout(renderMatch,300)}else{$('#match-feedback').textContent='Chưa khớp. Hãy so sánh Function và Mechanism, không chỉ hình dáng.';$$('.match-option.selected').forEach(x=>x.classList.add('wrong'));setTimeout(()=>{$$('.match-option').forEach(x=>x.classList.remove('selected','wrong'));app.match.nature=app.match.design=null},450)}}
$('#reset-match').addEventListener('click',()=>{app.match={nature:null,design:null,done:new Set()};$('#match-feedback').textContent='Ghép cặp đầu tiên để bắt đầu.';renderMatch()});renderMatch();

const functionData={Protect:['Tê tê: lớp vảy chồng','Vỏ bào ngư: composite nhiều lớp','Cây: phản ứng hóa học'],Cool:['Tổ mối: thông gió thụ động','Tai voi: tăng trao đổi nhiệt','Xương rồng: quản lý bức xạ'],Collect:['Bọ sa mạc: điểm ưa/kị nước','Gai xương rồng: dẫn giọt','Lá bromeliad: hình phễu'],Transport:['Gân lá: mạng phân nhánh','Mạch máu: phân phối đa cấp','Nấm: mạng mycelium'],Attach:['Gecko: lông vi mô','Burr: móc nhỏ','Trai: protein bám ướt'],Filter:['Cá voi tấm sừng: lọc dòng','Mang cá: trao đổi chọn lọc','Rễ ngập mặn: kiểm soát muối'],Store:['Lạc đà: quản lý năng lượng','Thân mọng: tích nước','Tổ ong: khoang mô-đun'],Sense:['Râu côn trùng: tín hiệu hóa học','Da cá: cảm nhận dòng','Cây: hướng sáng'],Repel:['Lá sen: giảm bám nước','Da cá mập: kiểm soát bám bẩn','Lông chim: cấu trúc chống ướt'],Regulate:['Khí khổng: đóng/mở','Cơ thể: homeostasis','Tổ mối: điều tiết khí']};
$('#function-grid').innerHTML=Object.keys(functionData).map(k=>`<button class="function-chip" data-function="${k}">${k}</button>`).join('');
$$('[data-function]').forEach(b=>b.addEventListener('click',()=>{$$('.function-chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#function-detail').innerHTML=`<p class="micro">FUNCTION · ${b.dataset.function.toUpperCase()}</p><h3>How does nature ${b.dataset.function.toLowerCase()}?</h3><ul>${functionData[b.dataset.function].map(x=>`<li>${x}</li>`).join('')}</ul><p>Đừng chọn sinh vật ngay. So sánh nhiều Strategy cho cùng Function.</p>`;markProgress('ask')}));

const biologize=[
 ['Thiết kế mái che sân trường giúp giảm nóng nhưng sử dụng ít điện.',['How can we build a cooler roof?','How does nature manage heat?','Which animal has a cool house?'],1,'Câu hỏi tập trung vào Function “manage heat”, không khóa vào mái hay một loài.'],
 ['Tạo bao bì bảo vệ đồ vật nhưng dùng ít vật liệu.',['How does nature protect with less material?','Which shell is the strongest?','How can we make plastic thicker?'],0,'Protect là Function; “with less material” giữ lại ràng buộc thiết kế.'],
 ['Thu nước mưa trên một bề mặt nhỏ.',['Which plant looks like a funnel?','How does nature collect and direct water?','How can we copy a cactus?'],1,'Collect và direct water mở ra nhiều Biological Strategies.'],
 ['Gắn vật lên tường nhưng có thể tháo ra nhiều lần.',['How does nature attach reversibly?','Which animal has sticky feet?','How can we make stronger glue?'],0,'“Attach reversibly” mô tả đúng chức năng và tính chất mong muốn.'],
 ['Giảm lực cản cho một phương tiện di chuyển trong nước.',['How does nature move efficiently through fluids?','Which fish is fastest?','How can we build a fish-shaped boat?'],0,'Câu hỏi Function không khóa vào một sinh vật hay hình dạng cụ thể.']
];let bioIndex=0;
function renderBio(){const [q,opts]=biologize[bioIndex];$('#bio-progress').textContent=`${bioIndex+1} / ${biologize.length}`;$('#bio-challenge').textContent=q;$('#bio-options').innerHTML=opts.map((x,i)=>`<button data-bio-answer="${i}"><b>${String.fromCharCode(65+i)}.</b> ${x}</button>`).join('');$('#bio-feedback').textContent='';$$('[data-bio-answer]').forEach(b=>b.addEventListener('click',()=>{const item=biologize[bioIndex],ok=+b.dataset.bioAnswer===item[2];$$('[data-bio-answer]').forEach(x=>x.disabled=true);b.classList.add(ok?'correct':'incorrect');if(!ok)$$('[data-bio-answer]')[item[2]].classList.add('correct');$('#bio-feedback').textContent=(ok?'Đúng. ':'Hãy thử tách Function khỏi sản phẩm. ')+item[3];if(ok)markProgress('ask')}))}
$('#next-bio').addEventListener('click',()=>{bioIndex=(bioIndex+1)%biologize.length;renderBio()});renderBio();

const strategies={cool:[['Termite mound','Passive ventilation','Porous channels and pressure differences move air.'],['Elephant ear','Heat dissipation','Large, vascular surfaces release heat.'],['Desert plant','Manage solar exposure','Orientation and surface geometry reduce heat gain.']],"collect water":[['Namib beetle','Condense droplets','Mixed wettable and repellent zones guide water.'],['Cactus spine','Direct droplets','Conical grooves move water toward the stem.'],['Bromeliad','Funnel water','Leaf geometry directs rain to a central reservoir.']],attach:[['Gecko','Dry reversible adhesion','Millions of tiny hairs create surface forces.'],['Burr','Mechanical hooks','Hooks catch loops and detach without glue.'],['Mussel','Wet adhesion','Proteins create strong bonds under water.']],protect:[['Abalone','Layered toughness','Hard tiles and soft interfaces stop cracks.'],['Pangolin','Overlapping armor','Scales combine coverage and mobility.'],['Turtle shell','Curved composite','Shape and layers distribute impact.']],filter:[['Baleen whale','Cross-flow filtration','Flow carries food along filter plates.'],['Manta ray','Ricochet separation','Particles bounce into a collection stream.'],['Mangrove root','Selective barrier','Membranes limit salt movement.']],"reduce drag":[['Shark skin','Riblet flow control','Aligned denticles organize near-surface flow.'],['Kingfisher','Smooth transition','Streamlined geometry reduces pressure change.'],['Dolphin','Compliant surface','Flexible skin interacts with turbulence.']]};
const searchKeys=Object.keys(strategies);$('#function-list').innerHTML=searchKeys.map(x=>`<option value="${x}">`).join('');$('#search-tags').innerHTML=searchKeys.map(x=>`<button data-search-tag="${x}">${x}</button>`).join('');
function searchNature(term){term=term.trim().toLowerCase();const key=searchKeys.find(k=>term.includes(k)||k.includes(term))||'cool';$('#nature-search').value=key;$('#strategy-results').innerHTML=`<p class="micro">DEMO RESULTS · ${key.toUpperCase()}</p>`+strategies[key].map((s,i)=>`<article class="strategy-card"><span>0${i+1}</span><div><h4>${s[0]}</h4><p><strong>${s[1]}</strong></p><p>${s[2]}</p></div></article>`).join('');markProgress('ask')}
$('#search-nature').addEventListener('click',()=>searchNature($('#nature-search').value));$('#nature-search').addEventListener('keydown',e=>{if(e.key==='Enter')searchNature(e.target.value)});$$('[data-search-tag]').forEach(b=>b.addEventListener('click',()=>searchNature(b.dataset.searchTag)));searchNature('cool');
const research=[['Identify Function','Viết 1-2 Functional Verbs mô tả thiết kế phải làm gì.'],['Search AskNature','Tìm ít nhất 3 Biological Strategies cho cùng Function.'],['Select','Chọn Strategy phù hợp nhất với criteria và constraints.'],['Understand','Ghi Organism, Function, Strategy, Mechanism và bằng chứng.'],['Abstract','Bỏ tên sinh vật; viết logic cấu trúc/quá trình → chức năng.'],['Apply','Sketch giải pháp mới và chỉ rõ điều gì được giữ, điều gì đổi.']];$('#research-steps').innerHTML=research.map(x=>`<li><h4>${x[0]}</h4><p>${x[1]}</p></li>`).join('');

const spiral=[['DEFINE','Xác định challenge, người dùng, criteria và constraints.'],['BIOLOGIZE','Chuyển nhu cầu thành câu hỏi “How does nature…?”'],['DISCOVER','Tìm nhiều sinh vật hoặc hệ sinh thái thực hiện cùng Function.'],['ABSTRACT','Tách Mechanism khỏi tên sinh vật thành Design Principle.'],['EMULATE','Phát triển, kết hợp và tạo prototype từ nguyên lý.'],['EVALUATE','Kiểm tra fit, function và Nature’s Unifying Patterns; quay lại cải tiến.']];
const nodePos=[[46,8],[77,24],[77,60],[45,76],[16,58],[15,25]];$('#spiral-nodes').innerHTML=spiral.map((s,i)=>`<button class="spiral-node" data-spiral="${i}" style="left:${nodePos[i][0]}%;top:${nodePos[i][1]}%">${i+1}<br>${s[0]}</button>`).join('');
function renderSpiral(i=0){$$('[data-spiral]').forEach((x,j)=>x.classList.toggle('active',i===j));$('#spiral-detail').innerHTML=`<strong>0${i+1}</strong><h3>${spiral[i][0]}</h3><p>${spiral[i][1]}</p><p class="think-prompt">Spiral reminder → Có bằng chứng mới? Hãy quay lại bước trước.</p>`;markProgress('abstract')}$$('[data-spiral]').forEach(b=>b.addEventListener('click',()=>renderSpiral(+b.dataset.spiral)));renderSpiral();
const pathData={challenge:['Design Challenge','Function','Biologize','Discover strategies','Abstract','Emulate'],biology:['Biological Strategy','Understand mechanism','Abstract principle','Find contexts','Design idea','Evaluate']};function renderPath(k){$('#path-flow').innerHTML=pathData[k].map((x,i)=>`${i?'<i>→</i>':''}<span>${x}</span>`).join('')}$$('[data-path]').forEach(b=>b.addEventListener('click',()=>{$$('[data-path]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderPath(b.dataset.path)}));renderPath('challenge');

const cases=[
 ['🪶','Kingfisher','Move across media','Streamlined beak reduces abrupt pressure change','Shape transitions gradually to reduce disturbance','Shinkansen nose','Còn phương tiện nào chuyển giữa hai môi trường?','#5ec3b4'],
 ['🍃','Lotus leaf','Stay clean','Hierarchical texture and wax reduce water contact','Reduce adhesion with multi-scale surface texture','Self-cleaning coating','Ứng dụng nào cần sạch mà không dùng hóa chất?','#8bae66'],
 ['🦎','Gecko','Attach reversibly','Microscopic hairs create weak forces across huge contact area','Multiply tiny contacts for strong, reversible attachment','Dry adhesive','Có thể dùng trong robot bảo trì như thế nào?','#f2ad5f'],
 ['🦈','Shark skin','Move / resist fouling','Aligned riblets organize flow and limit attachment','Use directional microgrooves to manage surface interaction','Riblet surfaces','Bệnh viện có thể học gì từ việc hạn chế bám?','#5a91b5'],
 ['🐜','Termite mound','Exchange gases','Porous walls and channels use wind pressure differences','Use geometry and variable openings to drive passive airflow','Building ventilation concept','Cơ chế có phù hợp khí hậu địa phương không?','#c59a62'],
 ['🌵','Desert organisms','Collect scarce water','Surface chemistry and geometry condense and direct droplets','Combine wettable points with channels toward storage','Water-harvesting surface','Làm sao tránh bụi làm tắc bề mặt?','#b7bd63'],
 ['🦴','Bone','Support with low mass','Material is added along stress paths and removed elsewhere','Place material only where loads require it','Lightweight structure','Sản phẩm nào đang dùng vật liệu đồng đều không cần thiết?','#d7cab4'],
 ['🐚','Abalone','Resist cracks','Hard mineral tiles and soft protein layers redirect cracks','Alternate hard units and compliant interfaces','Tough layered composite','Nguyên lý này có ích cho bao bì bảo vệ không?','#a8cbd1']
];
$('#case-gallery').innerHTML=cases.map((c,i)=>`<button class="case-card" data-case="${i}" style="--case-color:${c[8]}"><div class="case-icon">${c[0]}</div><small>CASE 0${i+1}</small><h3>${c[1]}</h3><p>${c[2]} → ${c[6]}</p><b>Open specimen ↗</b></button>`).join('');
$$('[data-case]').forEach(b=>b.addEventListener('click',()=>{const c=cases[+b.dataset.case];$('#case-modal-content').innerHTML=`<p class="kicker">CASE STUDY · ${c[1].toUpperCase()}</p><h2>${c[0]} ${c[1]}</h2><div class="case-chain"><div><small>THE CHALLENGE</small><p>Con người cần một cách để <strong>${c[2].toLowerCase()}</strong> hiệu quả hơn.</p></div><div><small>ASK NATURE</small><p>How does nature ${c[2].toLowerCase()}?</p></div><div><small>BIOLOGICAL STRATEGY</small><p>${c[3]}</p></div><div><small>ABSTRACT PRINCIPLE</small><p>${c[4]}</p></div><div><small>DESIGN</small><p>${c[5]}</p></div></div><p class="case-think">THINK → ${c[7]}</p>`;$('#case-modal').showModal();markProgress('discoverCases')}));$('.modal-close').addEventListener('click',()=>$('#case-modal').close());$('#case-modal').addEventListener('click',e=>{if(e.target===$('#case-modal'))$('#case-modal').close()});

const challenges=[['☀️','A','COOL OUR SCHOOL','Làm mát một không gian trong trường với ít năng lượng.'],['💧','B','LIVING WITH WATER','Thu, thoát hoặc trữ nước để thích nghi mưa lớn.'],['♻️','C','ZERO WASTE SCHOOL','Giữ vật liệu trong chu trình thay vì thành rác.'],['◐','D','SMART SHADE','Tạo hệ che nắng tự phản ứng với môi trường.']];
$('#challenge-picker').innerHTML=challenges.map((c,i)=>`<button class="challenge-card" data-challenge="${i}"><span>${c[0]}</span><small>CHALLENGE ${c[1]}</small><h3>${c[2]}</h3><p>${c[3]}</p></button>`).join('');
const fields=[['challenge','01 DESIGN CHALLENGE','What problem are we solving?','Vấn đề, người dùng, bối cảnh, criteria và constraints.'],['function','02 FUNCTION','What must the design DO?','Viết 1-2 Functional Verbs.'],['ask','03 ASK NATURE','How does nature ______?','Biologize Function và context.'],['models','04 BIOLOGICAL MODELS','Strategy 1 · Strategy 2 · Strategy 3','So sánh ít nhất ba chiến lược.'],['select','05 SELECT','Which strategy is most promising?','Giải thích theo criteria và constraints.'],['abstract','06 ABSTRACT','What is the Design Principle?','Không còn tên sinh vật.'],['ideate','07 IDEATE','What could we create?','Mô tả hoặc phác thảo ý tưởng.'],['evaluate','08 EVALUATE','Which Nature’s Patterns does it follow?','Nêu bằng chứng và một đánh đổi.']];
$('#canvas-grid').innerHTML=fields.map((f,i)=>`<div class="canvas-field ${i>5?'full':''}"><label for="canvas-${f[0]}">${f[1]}</label><small>${f[2]}</small><textarea id="canvas-${f[0]}" name="${f[0]}" placeholder="${f[3]}"></textarea></div>`).join('');
fields.forEach(f=>{$(`#canvas-${f[0]}`).value=app.canvas[f[0]]||''});
function saveCanvas(){fields.forEach(f=>app.canvas[f[0]]=$(`#canvas-${f[0]}`).value);storage.set('bioLabCanvas',app.canvas);$('#save-status').textContent='Đã lưu';markProgress('design');setTimeout(()=>$('#save-status').textContent='Tự động lưu',1000)}$('#design-canvas').addEventListener('input',()=>{clearTimeout(saveCanvas.timer);saveCanvas.timer=setTimeout(saveCanvas,400)});
$$('[data-challenge]').forEach(b=>b.addEventListener('click',()=>{$$('[data-challenge]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const c=challenges[+b.dataset.challenge];$('#canvas-title').textContent=c[2];$('#canvas-challenge').value=c[3];saveCanvas();toast(`Đã chọn ${c[2]}`)}));$('#print-canvas').addEventListener('click',()=>window.print());$('#reset-canvas').addEventListener('click',()=>{if(confirm('Xóa toàn bộ nội dung Design Canvas?')){fields.forEach(f=>$(`#canvas-${f[0]}`).value='');app.canvas={};storage.set('bioLabCanvas',{});toast('Design Canvas đã được làm mới')}});

$('#nature-sliders').innerHTML=patterns.map((p,i)=>`<div class="slider-row"><label for="slider-${i}">${p.vi}<small>${p.short}</small></label><input type="range" id="slider-${i}" min="1" max="5" value="3" data-slider><output for="slider-${i}">3</output></div>`).join('');
function updateScore(){const vals=$$('[data-slider]').map(x=>+x.value),score=vals.reduce((a,b)=>a+b,0)*2;$('#nature-score').textContent=score;$('#score-ring-fill').style.width=`${score}%`;const ranked=vals.map((v,i)=>[v,i]).sort((a,b)=>b[0]-a[0]),strong=patterns[ranked[0][1]].short,weak=patterns[ranked.at(-1)[1]].short;$('#score-feedback').textContent=`Thiết kế mạnh về ${strong}. Hãy cải thiện ${weak} và ghi bằng chứng cụ thể.`;markProgress('evaluate')}$$('[data-slider]').forEach(x=>x.addEventListener('input',()=>{x.nextElementSibling.value=x.value;updateScore()}));updateScore();

const quiz=[
 ['Multiple Choice','Thiết kế nào gần Biomimicry nhất?',['Ghế hình chiếc lá','Bề mặt học cơ chế tự làm sạch của lá sen','Đèn trang trí hình vỏ sò','Tường dùng cây thật'],1,'Biomimicry học Function, Strategy và Mechanism; không chỉ mượn hình hoặc dùng sinh vật.'],
 ['Identify Function','“Gai xương rồng dẫn giọt nước về thân” đang thực hiện Function nào?',['Attach','Collect / Transport water','Protect from impact','Communicate'],1,'Hãy dùng động từ chức năng: collect và transport water.'],
 ['True / False','Nature as Mentor nghĩa là xem thiên nhiên chủ yếu như kho tài nguyên.',['Đúng','Sai'],1,'Mentor là học và tôn trọng thiên nhiên, không chỉ khai thác.'],
 ['Nature’s Pattern','Tòa nhà tự mở cửa sổ khi CO₂ tăng phản ánh pattern nào?',['Recycle materials','Run on information','Use shape','Mutual benefits'],1,'Cảm biến nhận tín hiệu và hệ thống phản hồi bằng hành động.'],
 ['Case Analysis','Vì sao câu “How does nature manage heat?” tốt hơn “con vật nào có nhà mát?”',['Có ít từ hơn','Tập trung Function và mở nhiều strategy','Luôn cho một đáp án','Không cần hiểu cơ chế'],1,'Biologize bắt đầu bằng Function, không khóa vào một loài.'],
 ['Mechanism','Điều gì làm bề mặt lá sen giảm bám nước?',['Màu xanh','Vi cấu trúc kết hợp lớp kị nước','Kích thước lá','Mùi của lá'],1,'Cấu trúc đa cấp và tính chất bề mặt làm giảm diện tích tiếp xúc.'],
 ['Nature’s Pattern','Cấu trúc xương đặt vật liệu ở vùng chịu lực thể hiện bài học nào?',['Maximize mass','Optimize rather than maximize','Ignore information','Use rare resources'],1,'Xương cân bằng độ bền với khối lượng và chi phí năng lượng.'],
 ['Abstract','Design Principle nào trừu tượng tốt nhất từ tổ ong?',['Làm sản phẩm hình con ong','Sơn vàng đen','Dùng mô-đun lặp để tạo không gian hiệu quả','Dùng sáp ong'],2,'Nguyên lý tốt bỏ tên sinh vật và giữ logic cấu trúc-chức năng.'],
 ['Case Analysis','Hệ thống nước có nhiều nguồn phân tán đang tăng điều gì?',['Resilience','Biomorphism','Maximum growth','Surface color'],0,'Đa dạng, dự phòng và phân tán giúp duy trì chức năng khi có sự cố.'],
 ['Evaluate','Bao bì khó tách vật liệu yếu nhất ở pattern nào?',['Local response','Recycle all materials','Run on information','Mutual benefits'],1,'Vật liệu không thể tách sẽ khó quay lại chu trình.'],
 ['Pathway','Nhóm quan sát gecko trước rồi tìm ứng dụng đang đi theo hướng nào?',['Challenge → Biology','Biology → Design','Measure → Model','Test → Define'],1,'Nhóm bắt đầu từ một Biological Strategy rồi tìm bối cảnh thiết kế.'],
 ['Final Detective','Câu hỏi quan trọng nhất khi nhìn một chiếc lá là gì?',['Nó có đẹp không?','Nó đang giải quyết vấn đề gì?','Có thể sao chép màu nào?','Tên nó là gì?'],1,'Con mắt Biomimicry tìm Function và Strategy ẩn sau điều quan sát được.']
];
function renderQuiz(){const q=quiz[app.quiz.index];if(!q)return renderQuizResult();$('#quiz-progress').textContent=`Câu ${app.quiz.index+1} / ${quiz.length}`;$('#quiz-bar-fill').style.width=`${app.quiz.index/quiz.length*100}%`;$('#quiz-points').textContent=`${app.quiz.score} điểm`;$('#quiz-stage').innerHTML=`<div class="quiz-question"><span class="type-label">${q[0]}</span><h3>${q[1]}</h3></div><div class="quiz-options">${q[2].map((o,i)=>`<button data-quiz-answer="${i}"><b>${String.fromCharCode(65+i)}.</b> ${o}</button>`).join('')}</div><div id="quiz-explanation"></div>`;app.quiz.locked=false;$$('[data-quiz-answer]').forEach(b=>b.addEventListener('click',()=>answerQuiz(+b.dataset.quizAnswer)))}
function answerQuiz(i){if(app.quiz.locked)return;app.quiz.locked=true;const q=quiz[app.quiz.index],ok=i===q[3];if(ok)app.quiz.score++;$$('[data-quiz-answer]').forEach((b,j)=>{b.disabled=true;if(j===q[3])b.classList.add('correct');else if(j===i)b.classList.add('incorrect')});$('#quiz-explanation').innerHTML=`<div class="quiz-explanation"><strong>${ok?'Chính xác.':'Chưa chính xác.'}</strong> ${q[4]}</div><button class="button secondary quiz-next">${app.quiz.index===quiz.length-1?'Xem kết quả':'Câu tiếp theo'} →</button>`;$('.quiz-next').addEventListener('click',()=>{app.quiz.index++;renderQuiz()})}
function renderQuizResult(){const s=app.quiz.score,pct=Math.round(s/quiz.length*100),passed=pct>=80,title=passed?'Nature-Inspired Designer':s>=7?'Biomimicry Thinker':'Nature Explorer',icon=passed?'🌎':s>=7?'🧬':'🌱';$('#quiz-bar-fill').style.width='100%';$('#quiz-progress').textContent='Hoàn thành';const certificate=passed?`<section class="certificate-unlock"><p class="kicker">CERTIFICATE UNLOCKED</p><h4>Xuất Giấy chứng nhận hoàn thành</h4><p>Kiểm tra họ tên, chọn giáo viên hướng dẫn rồi xuất PDF để nộp lên Canvas.</p><form id="certificate-form"><label><span>Họ và tên học sinh</span><input name="studentName" value="${escapeHTML(app.profile.name)}" required></label><label><span>Lớp</span><input name="className" value="${escapeHTML(app.profile.className)}" required></label><label><span>Giáo viên / Người hướng dẫn</span><select name="teacher" required><option value="">Chọn giáo viên</option><option>Thầy Huỳnh Bảo Thiên</option><option>Cô Từ Song Ngân</option><option>Cô Dương Lê Hồng Thắm</option></select></label><button class="button primary" type="submit">Tạo và xuất chứng nhận PDF</button></form></section>`:`<section class="certificate-locked"><strong>Chứng nhận chưa được mở khóa</strong><p>Cần đạt tối thiểu 80%. Kết quả hiện tại: ${pct}%. Hãy ôn lại rồi thử lại.</p></section>`;$('#quiz-stage').innerHTML=`<div class="quiz-result"><div class="result-icon">${icon}</div><p class="kicker">${passed?'BADGE UNLOCKED':'QUIZ COMPLETED'}</p><h3>${title}</h3><p>Bạn trả lời đúng <strong>${s}/${quiz.length}</strong> câu — <strong>${pct}%</strong>.</p><p>${passed?'Bạn đã liên kết tốt Function, Mechanism và Nature’s Patterns.':s>=7?'Bạn đã có nền tảng tốt. Hãy mở lại Pattern Explorer để củng cố.':'Hãy quay lại Kho tình huống và luyện cách hỏi theo Function.'}</p>${certificate}<button class="button secondary" id="restart-quiz">Làm lại trắc nghiệm</button></div>`;markProgress('quiz');toast(passed?'Đã mở khóa chứng nhận!':`Kết quả ${pct}% — cần 80% để nhận chứng nhận.`);if(passed)$('#certificate-form').addEventListener('submit',printCertificate);$('#restart-quiz').addEventListener('click',()=>{app.quiz={index:0,score:0,locked:false};renderQuiz()})}
function printCertificate(event){event.preventDefault();const form=event.currentTarget,name=form.elements.studentName.value.trim(),className=form.elements.className.value.trim(),teacher=form.elements.teacher.value;if(!name||!className||!teacher){toast('Điền đủ họ tên, lớp và chọn giáo viên.');return}app.profile.name=name;app.profile.className=className;storage.set('bioStudentProfile',app.profile);renderStudentProfile();const date=new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date());$('#certificate-name').textContent=name;$('#certificate-class').textContent=className;$('#certificate-date').textContent=date;$('#certificate-teacher').textContent=teacher;document.body.classList.add('printing-certificate');window.print();setTimeout(()=>document.body.classList.remove('printing-certificate'),800)}
window.addEventListener('afterprint',()=>document.body.classList.remove('printing-certificate'));renderQuiz();

document.addEventListener('keydown',e=>{if(e.key==='Escape'){if($('#case-modal').open)$('#case-modal').close();toggleDrawer(false)}});
markProgress('discover');
