"use client";

import { useEffect, useMemo, useState } from "react";

type Pattern = {
  id: number; slug: string; icon: string; title: string; short: string;
  nature: string; design: string; question: string; tags: string[];
};

const patterns: Pattern[] = [
  {id:1,slug:"energy",icon:"☀",title:"Chỉ dùng năng lượng cần thiết",short:"Tận dụng nguồn năng lượng sẵn có, tái tạo và tại chỗ.",nature:"Chim condor lượn trên luồng khí nóng để tìm thức ăn với mức tiêu hao năng lượng rất thấp.",design:"Thu hồi nhiệt, chiếu sáng và thông gió tự nhiên; giảm nhu cầu trước khi bổ sung năng lượng.",question:"Giải pháp có thể đạt cùng chức năng với ít năng lượng hơn không?",tags:["năng lượng","hiệu quả"]},
  {id:2,slug:"recycle",icon:"↻",title:"Luân chuyển mọi vật liệu",short:"Trong tự nhiên, đầu ra của hệ này trở thành đầu vào của hệ khác.",nature:"Gỗ mục được nấm và nhiều sinh vật phân rã thành các cấu phần có thể tái sử dụng trong hệ sinh thái.",design:"Thiết kế dễ tháo rời, phân loại, sửa chữa và đưa vật liệu trở lại chu trình mới.",question:"Cuối vòng đời, từng vật liệu sẽ đi đâu?",tags:["vật liệu","tuần hoàn"]},
  {id:3,slug:"resilient",icon:"⌁",title:"Có khả năng phục hồi",short:"Duy trì chức năng nhờ đa dạng, dự phòng, phân tán và tự sửa chữa.",nature:"Thông lodgepole có nón chỉ mở sau nhiệt độ cao, giúp rừng tái sinh sau cháy.",design:"Tạo nhiều con đường thực hiện chức năng quan trọng; tránh một điểm hỏng duy nhất.",question:"Nếu một bộ phận hỏng, toàn hệ còn hoạt động không?",tags:["thích nghi","hệ thống"]},
  {id:4,slug:"optimize",icon:"≈",title:"Tối ưu thay vì tối đa",short:"Cân bằng hiệu quả với chi phí vật liệu, năng lượng và rủi ro.",nature:"Sinh vật không tăng trưởng vô hạn; đầu tư quá mức vào một đặc tính có thể làm giảm khả năng sống sót.",design:"Tối ưu nhiều mục tiêu trong toàn vòng đời thay vì chỉ tối đa tốc độ, sản lượng hay kích thước.",question:"Ta đang tối ưu toàn hệ hay chỉ một chỉ số?",tags:["cân bằng","hệ thống"]},
  {id:5,slug:"cooperation",icon:"∞",title:"Tạo lợi ích tương hỗ",short:"Mối quan hệ bền vững tạo giá trị cho nhiều thành phần.",nature:"Nấm rễ giúp cây hấp thụ khoáng; cây cung cấp đường tạo ra từ quang hợp cho nấm.",design:"Tìm cách để đầu ra, hạ tầng hoặc dữ liệu của một bên tạo ích lợi cho bên khác.",question:"Ai khác có thể hưởng lợi từ giải pháp này?",tags:["cộng sinh","hệ thống"]},
  {id:6,slug:"information",icon:"⌁",title:"Vận hành bằng thông tin",short:"Cảm nhận, truyền tín hiệu và phản hồi để điều chỉnh đúng lúc.",nature:"Cây keo phát tín hiệu ethylene khi bị ăn lá; các cây gần đó tăng chất phòng vệ.",design:"Dùng phản hồi vừa đủ, đúng thời điểm; để người dùng và hệ thống thấy hậu quả của hành động.",question:"Hệ thống cần cảm nhận điều gì để tự điều chỉnh?",tags:["thông tin","phản hồi"]},
  {id:7,slug:"chemistry",icon:"◌",title:"Dùng hóa học an toàn cho sự sống",short:"Tạo vật liệu trong nước, ở điều kiện thường và có thể phân hủy hữu ích.",nature:"Bọt biển Venus tạo khung silica tinh xảo từ nước biển ở nhiệt độ và áp suất môi trường.",design:"Ưu tiên dung môi nước, ít thành phần độc hại và vật liệu tương thích với chu trình sinh học.",question:"Vật liệu và quy trình có an toàn ở mọi giai đoạn không?",tags:["hóa học","vật liệu"]},
  {id:8,slug:"resources",icon:"▧",title:"Dùng tài nguyên dồi dào",short:"Ưu tiên vật liệu phổ biến tại chỗ; dùng tài nguyên hiếm thật tiết kiệm.",nature:"Ấu trùng caddisfly gom cát, sỏi, vỏ và cành nhỏ quanh mình để làm vỏ bảo vệ.",design:"Khảo sát vật liệu địa phương, phế phẩm và năng lực sẵn có trước khi nhập tài nguyên hiếm.",question:"Tài nguyên dồi dào nhất quanh bài toán là gì?",tags:["địa phương","vật liệu"]},
  {id:9,slug:"local",icon:"◎",title:"Thích nghi và đáp ứng tại chỗ",short:"Nhận biết điều kiện, chu kỳ và cơ hội của từng bối cảnh.",nature:"Tổ mối điều chỉnh đường hầm theo gió, độ ẩm, O₂ và CO₂ để duy trì cân bằng.",design:"Thiết kế theo khí hậu, văn hóa, người dùng, vật liệu và hạ tầng địa phương.",question:"Điều kiện riêng nào của nơi này phải định hình giải pháp?",tags:["địa phương","thích nghi"]},
  {id:10,slug:"shape",icon:"◒",title:"Dùng hình dạng để tạo chức năng",short:"Hình học phù hợp có thể thay thế vật liệu và năng lượng bổ sung.",nature:"Các dạng vây đuôi giúp cá ưu tiên tốc độ, lực đẩy hoặc khả năng cơ động.",design:"Tạo chức năng bằng bề mặt, cấu trúc, nếp gấp và hình học trước khi thêm cơ cấu phức tạp.",question:"Hình dạng có thể làm phần việc của vật liệu hoặc máy móc không?",tags:["hình dạng","hiệu quả"]},
];

const process = [
  ["01","Xác định thách thức","Viết nhu cầu bằng một động từ chức năng: giữ mát, bám, lọc, vận chuyển…"],
  ["02","Sinh học hóa câu hỏi","Hỏi: Tự nhiên làm thế nào để thực hiện chức năng này trong điều kiện tương tự?"],
  ["03","Khám phá chiến lược","Tìm trên AskNature; ghi lại cơ chế, không chỉ tên hoặc hình dáng sinh vật."],
  ["04","Khái quát nguyên lý","Tách logic cốt lõi khỏi ví dụ sinh học để có thể chuyển sang bối cảnh mới."],
  ["05","Mô phỏng & đánh giá","Tạo giải pháp rồi kiểm tra bằng 10 nguyên lý, bối cảnh, giới hạn và đánh đổi."],
];

export default function Home() {
  const [query,setQuery]=useState("");
  const [tag,setTag]=useState("tất cả");
  const [open,setOpen]=useState<number|null>(1);
  const [done,setDone]=useState<number[]>([]);
  useEffect(()=>{try{setDone(JSON.parse(localStorage.getItem("biomimicry-progress")||"[]"))}catch{}},[]);
  const toggleDone=(id:number)=>setDone(prev=>{const next=prev.includes(id)?prev.filter(x=>x!==id):[...prev,id];localStorage.setItem("biomimicry-progress",JSON.stringify(next));return next});
  const tags=["tất cả",...Array.from(new Set(patterns.flatMap(p=>p.tags)))];
  const filtered=useMemo(()=>patterns.filter(p=>(tag==="tất cả"||p.tags.includes(tag))&&`${p.title} ${p.short} ${p.nature} ${p.design}`.toLowerCase().includes(query.toLowerCase())),[query,tag]);
  return <main>
    <header className="nav"><a className="brand" href="#top"><span className="brandMark">B</span><span>BIOMIMICRY LAB</span></a><nav><a href="#patterns">10 nguyên lý</a><a href="#process">Quy trình</a><a href="#challenge">Thử thách</a></nav><a className="navCta" href="https://asknature.org/" target="_blank" rel="noreferrer">Khám phá AskNature ↗</a></header>

    <section className="hero" id="top"><div className="heroNoise"/><div className="heroCopy"><p className="eyebrow">PHÒNG THÍ NGHIỆM TỰ HỌC · CÔNG NGHỆ 12</p><h1>Tự nhiên không cho ta<br/><em>đáp án.</em> Tự nhiên cho ta<br/><span>chiến lược.</span></h1><p className="lead">Học 10 nguyên lý Biomimicry, khám phá cách sự sống giải quyết vấn đề và chuyển hóa bài học đó thành thiết kế phù hợp với con người.</p><div className="heroActions"><a className="primary" href="#patterns">Bắt đầu học</a><a className="textLink" href="#process">Xem cách áp dụng ↓</a></div></div><div className="heroFigure" aria-hidden="true"><div className="orbit orbit1"/><div className="orbit orbit2"/><div className="seed"><span>3,8</span><small>tỷ năm<br/>R&D</small></div><div className="label l1">THÍCH NGHI</div><div className="label l2">TỐI ƯU</div><div className="label l3">TÁI TẠO</div></div></section>

    <section className="manifesto"><p>Biomimicry là thực hành học hỏi và mô phỏng các chiến lược của tự nhiên để giải quyết thách thức của con người — với mục tiêu tạo ra những giải pháp <strong>phù hợp với sự sống.</strong></p><div className="three"><span><b>Model</b>Tự nhiên là hình mẫu</span><span><b>Measure</b>Tự nhiên là thước đo</span><span><b>Mentor</b>Tự nhiên là người thầy</span></div></section>

    <section className="patterns" id="patterns"><div className="sectionHead"><div><p className="eyebrow dark">BỘ CÔNG CỤ TƯ DUY</p><h2>10 nguyên lý thống nhất<br/>của tự nhiên</h2></div><div className="progress"><span>{done.length}/10 đã học</span><div><i style={{width:`${done.length*10}%`}}/></div></div></div>
      <div className="controls"><label className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm nguyên lý, ví dụ, vật liệu…" aria-label="Tìm kiếm nguyên lý"/></label><div className="tags">{tags.map(t=><button className={tag===t?"active":""} onClick={()=>setTag(t)} key={t}>{t}</button>)}</div></div>
      <div className="patternList">{filtered.map(p=><article className={`pattern ${open===p.id?"expanded":""}`} key={p.id}><button className="patternSummary" onClick={()=>setOpen(open===p.id?null:p.id)} aria-expanded={open===p.id}><span className="num">{String(p.id).padStart(2,"0")}</span><span className="pIcon">{p.icon}</span><span className="pTitle"><b>{p.title}</b><small>{p.short}</small></span><span className="expand">{open===p.id?"−":"+"}</span></button>{open===p.id&&<div className="patternBody"><div><p className="mini">TỰ NHIÊN LÀM GÌ?</p><p>{p.nature}</p></div><div><p className="mini">CHUYỂN SANG THIẾT KẾ</p><p>{p.design}</p></div><aside><p className="mini">CÂU HỎI THIẾT KẾ</p><blockquote>{p.question}</blockquote><div className="row"><a href={`https://toolbox.biomimicry.org/core-concepts/natures-unifying-patterns/${p.slug}/`} target="_blank" rel="noreferrer">Đọc nguồn ↗</a><button className={done.includes(p.id)?"checked":""} onClick={()=>toggleDone(p.id)}>{done.includes(p.id)?"✓ Đã học":"Đánh dấu đã học"}</button></div></aside></div>}</article>)}</div>
    </section>

    <section className="process" id="process"><div className="sectionHead light"><div><p className="eyebrow">TỪ SINH HỌC ĐẾN THIẾT KẾ</p><h2>Đừng sao chép hình dáng.<br/>Hãy chuyển giao logic.</h2></div><p className="sideNote">Một thiết kế Biomimicry thuyết phục phải nối được chuỗi: <b>Vấn đề → Chức năng → Chiến lược → Nguyên lý → Giải pháp.</b></p></div><div className="steps">{process.map(([n,t,d])=><div className="step" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div><div className="askBox"><div><p className="eyebrow">CÁCH TÌM TRÊN ASKNATURE</p><h3>Bắt đầu bằng một câu hỏi chức năng</h3></div><div className="askExamples"><span>How does nature <b>keep cool?</b></span><span>How does nature <b>filter water?</b></span><span>How does nature <b>attach?</b></span></div><a href="https://asknature.org/" target="_blank" rel="noreferrer">Mở AskNature ↗</a></div></section>

    <section className="challenge" id="challenge"><div className="challengeIntro"><p className="eyebrow dark">THỬ THÁCH TỰ HỌC</p><h2>Thiết kế không gian học<br/>mát mà không dùng điện.</h2><p>Học từ cơ chế thông gió của tổ mối, nhưng đừng dựng một công trình “trông giống tổ mối”. Hãy giữ lại logic và thích nghi nó với trường học của bạn.</p></div><div className="canvas"><div className="canvasHead"><span>DESIGN BRIEF 01</span><span>30–45 PHÚT</span></div><ol><li><b>Quan sát bối cảnh</b><span>Hướng gió, nắng, độ ẩm, số người, vật liệu địa phương.</span></li><li><b>Viết nguyên lý</b><span>Mô tả logic thông gió bằng 1–2 câu, không nhắc hình dáng tổ mối.</span></li><li><b>Tạo 3 phương án</b><span>Thay đổi cửa hút, cửa thoát, chiều cao và đường đi của không khí.</span></li><li><b>Thêm giới hạn</b><span>Ngân sách giảm 50% hoặc diện tích giảm một nửa.</span></li><li><b>Đánh giá</b><span>Dùng ít nhất 4 trong 10 nguyên lý để phản biện thiết kế.</span></li></ol><button onClick={()=>window.print()}>In phiếu thử thách</button></div></section>

    <section className="check"><p className="eyebrow dark">TỰ KIỂM TRA</p><h2>Đây có thật sự là Biomimicry?</h2><div className="checkGrid"><div><span>01</span><h3>Có bằng chứng sinh học?</h3><p>Bạn giải thích được cơ chế tự nhiên bằng nguồn đáng tin cậy.</p></div><div><span>02</span><h3>Có chuyển giao chức năng?</h3><p>Giải pháp giữ logic cốt lõi, không chỉ bắt chước hình thức.</p></div><div><span>03</span><h3>Có phù hợp bối cảnh?</h3><p>Người dùng, môi trường, vật liệu, chi phí và an toàn đã được xem xét.</p></div><div><span>04</span><h3>Có phù hợp với sự sống?</h3><p>Giải pháp hướng đến hệ thống bền vững, tuần hoàn và có lợi lâu dài.</p></div></div></section>

    <footer><div><span className="brandMark">B</span><h2>Hãy hỏi tự nhiên.</h2><p>Mỗi thiết kế là một cơ hội để con người học cách sống tốt hơn trên Trái Đất.</p></div><div className="sources"><p className="mini">NGUỒN HỌC TẬP CHÍNH THỨC</p><a href="https://toolbox.biomimicry.org/core-concepts/natures-unifying-patterns/" target="_blank" rel="noreferrer">Biomimicry Toolbox ↗</a><a href="https://asknature.org/" target="_blank" rel="noreferrer">AskNature ↗</a><a href="https://biomimicry.org/" target="_blank" rel="noreferrer">Biomimicry Institute ↗</a><small>Nội dung tiếng Việt được biên soạn phục vụ học tập; nguồn gốc và bản quyền thuộc các tổ chức được dẫn liên kết.</small></div></footer>
  </main>
}
